#!/usr/bin/env python
'''Protogen, the AIIP interface generator

Usage: protogen <inputfile> [--debug] [<outputfile>]
'''

if __name__ != '__main__':
    raise 'This module is not meant to be imported'

from docopt import docopt
import argparse
import sys

from parser import ProtogenParser

args = docopt(__doc__, version='Protogen 0.0.1')
debug = args["--debug"]
with open(args["<inputfile>"]) as inp:
    text = inp.read()

parser = ProtogenParser()
ast = parser.parse(text, rule_name='protocol', comments_re="#.*", trace=debug)

if debug:
    import json
    print("AST:")
    print(ast)
    print("JSON:")
    print(json.dumps(ast, indent=2))

